# Generated by Django 5.0.2 on 2024-03-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
