# Generated by Django 5.0.2 on 2024-03-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0004_news_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
